title: 2022 IEEE Video and Image Processing Cup
description: Synthetic Image Detection Challenge
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
github:
  is_project_page: false
show_downloads: false
